import type { AppState } from "@/src/types";

export const mockData: Partial<AppState> = {
  user: {
    id: "1",
    name: "John Doe",
    email: "john@example.com",
    avatar: "JD",
  },
  balance: 45750.8,
  transactions: [
    {
      id: "TXN001",
      date: "2024-01-15",
      description: "Salary Payment",
      recipient: "Acme Corp",
      category: "Income",
      amount: 5000.0,
      status: "completed",
      type: "credit",
    },
    {
      id: "TXN002",
      date: "2024-01-14",
      description: "Grocery Shopping",
      recipient: "Whole Foods",
      category: "Groceries",
      amount: -125.5,
      status: "completed",
      type: "debit",
    },
    {
      id: "TXN003",
      date: "2024-01-14",
      description: "Netflix Subscription",
      recipient: "Netflix Inc",
      category: "Entertainment",
      amount: -15.99,
      status: "completed",
      type: "debit",
    },
     {
      id: "TXN001",
      date: "2024-01-15",
      description: "Salary Payment",
      recipient: "Acme Corp",
      category: "Income",
      amount: 5000.0,
      status: "completed",
      type: "credit",
    },
    {
      id: "TXN002",
      date: "2024-01-14",
      description: "Grocery Shopping",
      recipient: "Whole Foods",
      category: "Groceries",
      amount: -125.5,
      status: "completed",
      type: "debit",
    },
    {
      id: "TXN003",
      date: "2024-01-14",
      description: "Netflix Subscription",
      recipient: "Netflix Inc",
      category: "Entertainment",
      amount: -15.99,
      status: "completed",
      type: "debit",
    },
     {
      id: "TXN001",
      date: "2024-01-15",
      description: "Salary Payment",
      recipient: "Acme Corp",
      category: "Income",
      amount: 5000.0,
      status: "completed",
      type: "credit",
    },
    {
      id: "TXN002",
      date: "2024-01-14",
      description: "Grocery Shopping",
      recipient: "Whole Foods",
      category: "Groceries",
      amount: -125.5,
      status: "completed",
      type: "debit",
    },
    {
      id: "TXN003",
      date: "2024-01-14",
      description: "Netflix Subscription",
      recipient: "Netflix Inc",
      category: "Entertainment",
      amount: -15.99,
      status: "completed",
      type: "debit",
    },
     {
      id: "TXN001",
      date: "2024-01-15",
      description: "Salary Payment",
      recipient: "Acme Corp",
      category: "Income",
      amount: 5000.0,
      status: "completed",
      type: "credit",
    },
    {
      id: "TXN002",
      date: "2024-01-14",
      description: "Grocery Shopping",
      recipient: "Whole Foods",
      category: "Groceries",
      amount: -125.5,
      status: "completed",
      type: "debit",
    },
    {
      id: "TXN003",
      date: "2024-01-14",
      description: "Netflix Subscription",
      recipient: "Netflix Inc",
      category: "Entertainment",
      amount: -15.99,
      status: "completed",
      type: "debit",
    },
    
  ],
  contacts: [
    {
      id: "1",
      name: "John Smith",
      username: "@johnsmith",
      phone: "+1 (555) 123-4567",
      email: "john@example.com",
      avatar: "JS",
      favorite: true,
      recent: true,
    },
    {
      id: "2",
      name: "Sarah Johnson",
      username: "@sarahj",
      phone: "+1 (555) 987-6543",
      email: "sarah@example.com",
      avatar: "SJ",
      favorite: true,
    },
  ],
  savingsGoals: [
    {
      id: "1",
      title: "Vacation Fund",
      target: 5000,
      current: 3400,
      daysLeft: 45,
      icon: "target",
    },
    {
      id: "2",
      title: "New Car",
      target: 25000,
      current: 11250,
      daysLeft: 180,
      icon: "award",
    },
  ],
  notifications: [
    {
      id: 1,
      title: "Bill Due Tomorrow",
      message: "Your electricity bill of $89.50 is due tomorrow",
      type: "warning",
      timestamp: "2024-01-15T10:00:00Z",
    },
    {
      id: 2,
      title: "Savings Goal Reached!",
      message: "You've reached your vacation savings goal! 🎉",
      type: "success",
      timestamp: "2024-01-15T09:00:00Z",
    },
  ],
  spendingCategories: [
    { name: "Groceries", amount: 2450.0, percentage: 28, color: "bg-blue-500", trend: "+5%" },
    { name: "Utilities", amount: 1850.0, percentage: 21, color: "bg-green-500", trend: "-2%" },
    { name: "Entertainment", amount: 1200.0, percentage: 14, color: "bg-purple-500", trend: "+12%" },
    { name: "Transport", amount: 980.0, percentage: 11, color: "bg-orange-500", trend: "-8%" },
    { name: "Others", amount: 2270.5, percentage: 26, color: "bg-gray-500", trend: "+3%" },
  ],
};
