import type { AppState } from "@/src/types";

export const mockData: Partial<AppState> = {
  user: {
    id: "1",
    name: "Peh Jos",
    email: "john@example.com",
    avatar: "PJ",
  },
  balance: 45750.8,
transactions: [
    {
      id: "TXN001",
      date: "2024-01-15",
      description: "Salary Payment",
      recipient: "Acme Corp",
      category: "Income",
      amount: 5000.0,
      status: "completed",
      type: "credit",
    },
    {
      id: "TXN002",
      date: "2024-01-14",
      description: "Grocery Shopping",
      recipient: "Whole Foods",
      category: "Groceries",
      amount: -125.5,
      status: "completed",
      type: "debit",
    },
    {
      id: "TXN003",
      date: "2024-01-14",
      description: "Netflix Subscription",
      recipient: "Netflix Inc",
      category: "Entertainment",
      amount: -15.99,
      status: "completed",
      type: "debit",
    },
    {
      id: "TXN004",
      date: "2024-01-13",
      description: "Gas Station",
      recipient: "Shell",
      category: "Transportation",
      amount: -45.20,
      status: "failed",
      type: "debit",
    },
    {
      id: "TXN005",
      date: "2024-01-12",
      description: "Coffee Shop",
      recipient: "Starbucks",
      category: "Food & Dining",
      amount: -8.75,
      status: "completed",
      type: "debit",
    },
    {
      id: "TXN006",
      date: "2024-01-12",
      description: "Online Transfer",
      recipient: "Savings Account",
      category: "Transfer",
      amount: -500.0,
      status: "completed",
      type: "debit",
    },
    {
      id: "TXN007",
      date: "2024-01-11",
      description: "Freelance Project",
      recipient: "TechStart LLC",
      category: "Income",
      amount: 1200.0,
      status: "pending",
      type: "credit",
    },
    {
      id: "TXN008",
      date: "2024-01-10",
      description: "Electric Bill",
      recipient: "ConEd",
      category: "Utilities",
      amount: -89.34,
      status: "completed",
      type: "debit",
    },
    {
      id: "TXN009",
      date: "2024-01-10",
      description: "Amazon Purchase",
      recipient: "Amazon",
      category: "Shopping",
      amount: -67.99,
      status: "failed",
      type: "debit",
    },
    {
      id: "TXN010",
      date: "2024-01-09",
      description: "Gym Membership",
      recipient: "Planet Fitness",
      category: "Health & Fitness",
      amount: -29.99,
      status: "pending",
      type: "debit",
    },
    {
      id: "TXN011",
      date: "2024-01-08",
      description: "Restaurant Dinner",
      recipient: "Olive Garden",
      category: "Food & Dining",
      amount: -42.15,
      status: "completed",
      type: "debit",
    },
    {
      id: "TXN012",
      date: "2024-01-07",
      description: "Phone Bill",
      recipient: "Verizon",
      category: "Utilities",
      amount: -75.00,
      status: "pending",
      type: "debit",
    }
  ],
  contacts: [
    {
      id: "1",
      name: "John Smith",
      username: "@johnsmith",
      phone: "+1 (555) 123-4567",
      email: "john@example.com",
      avatar: "JS",
      favorite: true,
      recent: true,
    },
    {
      id: "2",
      name: "Sarah Johnson",
      username: "@sarahj",
      phone: "+1 (555) 987-6543",
      email: "sarah@example.com",
      avatar: "SJ",
      favorite: true,
    },
  ],
  savingsGoals: [
    {
      id: "1",
      title: "Vacation Fund",
      target: 5000,
      current: 3400,
      daysLeft: 45,
      icon: "target",
    },
    {
      id: "2",
      title: "New Car",
      target: 25000,
      current: 11250,
      daysLeft: 180,
      icon: "award",
    },
  ],
  spendingCategories: [
    { name: "Groceries", amount: 2450.0, percentage: 28, color: "bg-blue-500", trend: "+5%" },
    { name: "Utilities", amount: 1850.0, percentage: 21, color: "bg-green-500", trend: "-2%" },
    { name: "Entertainment", amount: 1200.0, percentage: 14, color: "bg-purple-500", trend: "+12%" },
    { name: "Transport", amount: 980.0, percentage: 11, color: "bg-orange-500", trend: "-8%" },
  ],
};
